#!/bin/sh

if [ -f "$1" ] ; then
    case "$1" in
        *.tar.bz2|*.tbz2) tar xvjf "$1";;
        *.tar.gz|*.tgz) tar xvzf "$1";;
        *.lzma) unlzma "$1";;
        *.bz2) bunzip2 "$1";;
        *.rar) unrar x -ad "$1";;
        *.gz) gunzip "$1";;
        *.tar|*.tar.xz) tar xpvf "$1";;
        *.zip) unzip "$1";;
        *.Z) uncompress "$1";;
        *.7z) 7z x "$1";;
        *.xz) unxz "$1";;
        *) printf "don\'t know how to extract that!";;
    esac
else
    printf "\"%s\" : no such file!\n" "$1"
fi
